BIRT OpenSource: an error to run report using Report Engine(OSGI) Fixed java.lang.IncompatibleClassChangeError: Class org.apache.batik.css.pa rser.Parser does not implement the requested interface org.w3c.css.sac.Parser due to batik 1.8 incompatible with 1.7