Bug#535133 Fixed two problems after rollbacking to batik 1.7: 1. non-osgi runtime package and non-osgi war don't work. This is caused by multiple batik versions, and this is not allowed in non-osgi package. 2. osgi war throws java.lang.IncompatibleClassChangeError: Class org.apache.batik.css.parser.Parser does not implement the requested interface org.w3c.css.sac.Parser    at org.eclipse.birt.report.engine.css.engine.CSSEngine.parsePropertyValue(CSSEngine.java:127). This is caused by org.w3c.css.sac class loading difference between batik 1.7 and 1.9. Batik 1.7 loads it from plugin but 1.9 loads it from api jar. Need to adjust loading sequence for org.w3c.css.sac from batik client. Also add some fragments to resolve linkage error from 1.7.