Fix chart core tests #685
Added o.a.batik.dom.birt.ext to birt feature

Added batik.ext 1.14 to target

Disable the test so that it can at least run locally.

This is a fragment extending batik.dom so that
it can see org.apache.batik.w3c.dom

It solves the following dependency issue:

java.lang.NoClassDefFoundError:
org/apache/batik/w3c/dom/ElementTraversal
	at org.eclipse.birt.chart.tests.device.render.ImageOutputBaseTest.runTest(ImageOutputBaseTest.java:100)
Caused by: java.lang.ClassNotFoundException:
org.apache.batik.w3c.dom.ElementTraversal cannot be found by
org.apache.batik.dom_1.14.0.v20210324-0332
	at org.eclipse.birt.chart.tests.device.render.ImageOutputBaseTest.runTest(ImageOutputBaseTest.java:100)